name: Build

on:
  push:
    branches:
      - main
      # - development

jobs:
# Get all the dependencies (ROS2, o3de etc.)
# Initialize the empty project
# attach the gem to it
# build the project
  build:
    name: build
    runs-on: ubuntu-20.04
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        rosdistro: [galactic]
    env:
      ROS_DISTRO: ${{ matrix.rosdistro }}
    steps:
      - name: O3DE ROS 2 Gem checkout
        uses: actions/checkout@v3
        with:
          repository: RobotecAI/o3de-ros2-gem
          path: o3de-ros2-gem
      - name: O3DE checkout
        uses: actions/checkout@v3
        with:
          repository: o3de/o3de
          path: o3de
      - name: ROS 2 setup
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.rosdistro }}


