name: CodeChecks

on:
  push:
    branches:
      - main

jobs:
  cpp-linter:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          repository: RobotecAI/o3de-ros2-gem
          path: o3de-ros2-gem
          version: 
      - uses: cpp-linter/cpp-linter-action@v1.4.4
        id: linter
        with:
          style: file
          repo-root: o3de-ros2-gem

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
      