name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docgen:
    name: generate documentation test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gem repo
        uses: actions/checkout@v3
        with:
          repository: RobotecAI/o3de-ros2-gem
          path: o3de-ros2-gem
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Generate documentation
        uses: langroodi/doxygenize@v1.6.3
        with:
          doxygenconf: Doxyfile
          htmloutput: docs/
          ghpagesdir: docs/githubpages